# Module manifest for module 'module'
#
# Generated by: Tristan
#
# Generated on: 06/06/2022 18:27:19
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Tools.BaseModuleGenerator.psm1'

# Version number of this module.
ModuleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = 'aed04a77-6422-49f3-811b-33ac8ae61332'

# Author of this module
Author = 'TLU'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = ''

# Description of the functionality provided by this module
Description = 'Module used to generate basic module folder with .psd1 and .psm1'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = '5.1'

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
#RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @()

# Functions to export from this module
FunctionsToExport =  @(
	'Add-ExigenceObjectToWord',
	'Add-WordStyleFromDictionary',
	'Convert-MarkdownToWord',
	'Get-ExigenceLineType',
	'Get-ExigenceObjectList',
	'New-ExcelTableOLEObject',
	'New-ExigenceObject',
	'New-ExigenceTableObject',
	'New-ImageOLEObject'
)

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
#VariablesToExport = @(
#)

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
	'.\Dictionary\LinkTypeToStyle.ps1',
	'.\Dictionary\StyleDictionary.ps1',
	'.\Public\Add-ExigenceObjectToWord.ps1',
	'.\Public\Add-WordStyleFromDictionary.ps1',
	'.\Public\Convert-MarkdownToWord.ps1',
	'.\Public\Get-ExigenceLineType.ps1',
	'.\Public\Get-ExigenceObjectList.ps1',
	'.\Public\New-ExcelTableOLEObject.ps1',
	'.\Public\New-ExigenceObject.ps1',
	'.\Public\New-ExigenceTableObject.ps1',
	'.\Public\New-ImageOLEObject.ps1',
	'.\fenster.ExigenceConverter.psm1',
	'.\fenster.ExigenceConverter.psd1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}